#!/usr/bin/env python3
"""Merge public/generated/*/manifest.json into public/generated.js.

Rerun whenever new assets land in generated/:  python3 build-media-map.py
Pages reference assets from the public site root.
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
PUBLIC = HERE / 'public'
GEN = PUBLIC / 'generated'

entries = {}

def load(kind):
    p = GEN / kind / 'manifest.json'
    return json.load(open(p))['items'] if p.exists() else []

for it in load('fan-images'):
    if it.get('status') != 'completed':
        continue
    w, h = (int(x) for x in it['size'].split('x'))
    e = entries.setdefault(it['id'], {})
    e['img'] = it['file'].replace('generated/', 'generated/', 1)
    e.setdefault('w', w); e.setdefault('h', h)

for it in load('fan-videos'):
    if it.get('status') != 'completed':
        continue
    w, h = (int(x) for x in it['size'].split('x'))
    e = entries.setdefault(it['id'], {})
    e['vid'] = it['file']
    if it.get('thumbnail'):
        e['thumb'] = it['thumbnail']
    # video dims win: if both exist the card plays the video, so match its aspect
    e['w'], e['h'] = w, h

out = PUBLIC / 'generated.js'
out.write_text(
    '// AUTOGENERATED by build-media-map.py — do not edit by hand.\n'
    '// id -> { img?, vid?, thumb?, w, h } (paths relative to repo root;\n'
    '// served from the public site root)\n'
    'export const GENERATED = '
    + json.dumps(entries, indent=1, sort_keys=True)
    + ';\n')
print(f'wrote {out} with {len(entries)} assets '
      f'({sum(1 for e in entries.values() if "vid" in e)} videos, '
      f'{sum(1 for e in entries.values() if "img" in e)} images)')
